help: help-sim
clean: clean-sim
# CONDA=~/miniconda3/bin/conda
TOP?=counter
#test bench del proyecto para la simulación
tb?=$(TOP)_tb.v
# Módules .v que hacen parte del proyecto
MODULES?=

MK_SIM=../../../makefile/sim.mk
include $(MK_SIM)
