firmware_words:
	make -C firmware_words_src/


asm-build:
	make -C asm/
asm-clean:
	make -C asm/ clean

#rtl:
#	make -C rtl/

c-build:
	make -C c-code/
c-clean:
	make -C c-code/ clean

#	make -C firmware_words_src/ clean
	
	

