/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module top (
  input \I0.1 ,
  input \I0.2 ,
  input \I0.3 ,
  output \Q0.1 ,
  output \Q0.2 ,
  output \Q0.3 
);
  wire \Q0.3_temp ;
  assign \Q0.3_temp  = (~ \I0.3  & ~ (\I0.1  & \I0.2 ));
  assign \Q0.1  = \Q0.3_temp ;
  assign \Q0.2  = \I0.3 ;
  assign \Q0.3  = \Q0.3_temp ;
endmodule
