firmware_words:
	make -C firmware_words_src/
firmware_words_clean:
	make -C firmware_words_src/ clean

asm-build:
	make -C asm/
asm-clean:
	make -C asm/ clean

c-build:
	make -C c-code/ all
c-clean:
	make -C c-code/ clean
