/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module top (
  input I01,
  input I02,
  input I03,
  output Q01,
  output Q02,
  output Q03
);
  wire Q03_temp;
  assign Q03_temp = (~ I03 & ~ (I01 & I02));
  assign Q01 = Q03_temp;
  assign Q02 = I03;
  assign Q03 = Q03_temp;
endmodule
