firmware_words:
	make -C firmware_words_src/

c-build:
	make -C c/

asm-build:
	make -C asm/

#rtl:
#	make -C rtl/
	
clean:
	make -C c/ clean
	make -C asm/ clean
#	make -C firmware_words_src/ clean
	
	

