include ../../../makefile/altera-c4e6e10.mk

TOP=top
#test bench del proyecto para la simulación
tb=$(TOP)_tb.v
# Módules .v que hacen parte del proyecto
MODULES=./fulladder.v ./halfadder.v
# # Ruta donde está quartus instalado
# PATH_QUARTUS=/home/johnny/gitPackages/quartus/quartus/bin
# # Cable programador
# CABLE=USB-Blaster
