/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module puntoC (
  input a,
  input b,
  input c,
  input d,
  output x
);
  assign x = (~ (~ (~ a | b) & ~ (b & c)) | d);
endmodule
